### ISSUE TITLE
US1 - view artists 

### ISSUE THREAD

**Issue by oektemkalkan** [oektemkalkan/capstone-project#1]
## Value Proposition

**As a User**
**I want to** see all available concerts by category after clicking on POP or RAP
**so that** I can choose where and when I want to go.
​

## Description

gray color -> preview

you should see the ones highlighted in **blue**

![US1](https://github.com/oektemkalkan/capstone-project/assets/128001557/0971ac5c-578c-4388-9e50-21c94b6d019f)
![US1 1](https://github.com/oektemkalkan/capstone-project/assets/128001557/26737313-86cc-49fa-812d-6746d4f097e2)

## Acceptance Criteria

- [ ] main page should have two buttons (POP / RAP)
- [ ] artists should be visible on the respective pages 
- [ ] a back button that switches to the main page
      ​

## Tasks
- [ ] Add the Component Button (PopButton.js, RapButton.js, BackButton.js)
- [ ] Add the Components POP and RAP (PopPage.js, RapPage.js
- [ ] Add POP / RAP button on the main page to change sides
- [ ] Add the Component db for database (connect.js, Artist.js (mongoose))
- [ ] connect database so you can see the artists (picture, name, rating, price) in both categories -> POP and RAP page
- [ ] Add a button that goes back one page when clicked
      ​

## Complexity

M
