### ISSUE TITLE
US7 -  multiple tickets

### ISSUE THREAD

**Issue by oektemkalkan** [oektemkalkan/capstone-project#10]
## Value Proposition

**As a** User
**I want to** decide how many tickets I add to the shopping cart
**so that** I can order for friends too.
​

## Description

gray color -> preview

you should see the ones highlighted in blue

![US7](https://github.com/oektemkalkan/capstone-project/assets/128001557/78543704-6c8d-419a-9d14-e8768ce2716c)

## Acceptance Criteria

- [ ] changing the number of tickets at the details page
- [ ] price should double or triple depending on how many tickets you add
      ​

## Tasks

- [ ] create a branch
- [ ] Add a function that calculates the price of multiple tickets
- [ ] Add a function which shows the number of your tickets between - +
      ​

## Complexity

L
