### ISSUE TITLE
US2 -  shopping cart

### ISSUE THREAD

**Issue by oektemkalkan** [oektemkalkan/capstone-project#2]
## Value Proposition

**As a** User
**I want to** add a ticket to my shopping cart
**so that** I can see the concert ticket I want to buy.
​

## Description

gray color -> preview

you should see the ones highlighted in **blue**

![US2](https://github.com/oektemkalkan/capstone-project/assets/128001557/8c1abc5c-51e0-4712-8e14-b04947a822c6)

## Acceptance Criteria

- [ ] more information when clicking on a artist
- [ ] you can add a ticket when clicking on the price
- [ ] shopping cart page to see all tickets
      ​

## Tasks

- [ ] create a branch
- [ ] display all information after clicking on a artist
- [ ] the price should be a button to add a ticket 
- [ ] built shopping cart page which shows the tickets
      ​

## Complexity

M
