### ISSUE TITLE
US3 - submit or delete order

### ISSUE THREAD

**Issue by oektemkalkan** [oektemkalkan/capstone-project#3]
## Value Proposition

**As a** User
**I want to** to confirm or delete my order 
**so that** I can choose whether to buy it or not.
​

## Description

gray color -> preview

you should see the ones highlighted in **blue**
​
![US3](https://github.com/oektemkalkan/capstone-project/assets/128001557/33e676c0-e474-4a88-a94c-ff581f90c445)

## Acceptance Criteria

- [ ] deleting orders should work
- [ ] buy button to submit the order
- [ ] after the purchase, a  message should pop up
      ​

## Tasks

- [ ] create a branch
- [ ] add the component Delete
- [ ] built the delete button
- [ ] built the buy button as an submit
- [ ] write a ´success´ message after confirmation of purchase,
       it should pop up on the same page
      ​

## Complexity

M

**Comment by ninaassmann** [comment]
how do you get back after the success pop up?

everything else LGTM

**Comment by NicoleHoerner** [comment]
There are many things you are going to do. I suggest to split it into different user stories, maybe for each button. But that's up to you and just a preference I think!
So go ahead anyways😃
