### ISSUE TITLE
US4 - view order

### ISSUE THREAD

**Issue by oektemkalkan** [oektemkalkan/capstone-project#4]
## Value Proposition

**As a** User
**I want to** have a look on my order
**so that** I can be sure that I added the right ticket to my shopping cart.
​

## Description

gray color -> preview

you should see the ones highlighted in blue

![US4](https://github.com/oektemkalkan/capstone-project/assets/128001557/43f34347-db69-455b-922d-a40e1a42c691)

## Acceptance Criteria

- [ ] order should be clickable
- [ ] after click, a new page should open which shows the details of the ticket
      ​

## Tasks

- [ ] create a branch
- [ ] Add the Component Details
- [ ] DetailsPage should show the info of the ticket
      ​

## Complexity

S

**Comment by CJAkkuec** [comment]
> built the button to delete reviews
Deleting a review would be its own user story, along with the button. The button would only be created and rendered as part of the review component once the feature is ready to be used.

**Comment by NicoleHoerner** [comment]
I believe it was good to divide the user story.
LGTM
