### ISSUE TITLE
US5 - rating

### ISSUE THREAD

**Issue by oektemkalkan** [oektemkalkan/capstone-project#5]
## Value Proposition

**As a** User
**I want to** write a review 
**so that** other people can read my recommendation about the artist.
​

## Description

gray color -> preview

you should see the ones highlighted in blue
​
![US5](https://github.com/oektemkalkan/capstone-project/assets/128001557/7fa3e9dd-92b5-42da-96e5-5ea9c3c90798)
![US5 1](https://github.com/oektemkalkan/capstone-project/assets/128001557/47e732a8-65cc-4fe3-8445-1ebf93290273)

## Acceptance Criteria

- [ ] you can write reviews 
- [ ] the rating on the left should be clickable to open review page
- [ ] you can delete reviews
      ​

## Tasks

- [ ] create a branch
- [ ] add a rating field
- [ ] add the component Rating
- [ ] Built the Submit button to add reviews
- [ ] built the delete button
      ​

## Complexity

L

**Comment by NicoleHoerner** [comment]
This is indeed a short user story and I find shorter US better than if they are too large. Nevertheless a few more tasks would be nice. Maybe next time. I understand that the button is being created and rendered as part of the review component.
Suggestions to add (but is up to you):
Acceptance Criteria: the review is no longer visible after deletion.
Tasks: 
Redirect the user to the review page/or other page after successful deletion.

**Comment by shrocket** [comment]
Hi! Your description says that there should be some gray and a trashcan icon, but I find neither of these?
Both of the acceptance criteria worked! 
I did have a little trouble though, after entering a review, finding that review so that I could delete it.
I am aware that I'm kind of an "outsider" here, so I don't really know what processes are being used in your bootcamp, but I'm going to mark this with a ✔️ because I would like to hear from you about the discrepancies between the description and the acceptance criteria before I approve. I hope that's ok. Please let me know if you have any questions!

**Comment by oektemkalkan** [comment]
> Hi! Your description says that there should be some gray and a trashcan icon, but I find neither of these? Both of the acceptance criteria worked! I did have a little trouble though, after entering a review, finding that review so that I could delete it. I am aware that I'm kind of an "outsider" here, so I don't really know what processes are being used in your bootcamp, but I'm going to mark this with a ✔️ because I would like to hear from you about the discrepancies between the description and the acceptance criteria before I approve. I hope that's ok. Please let me know if you have any questions!

Hi, the description is just a preview of what the page should show and the "trashcan icon" is not a function its just a style. The gray things have already been programmed in previous user stories. What is important is the blue one (delete button)
